# Generated by Django 3.2.4 on 2021-06-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210616_0928'),
    ]

    operations = [
    ]
